### ISSUE TITLE
Error: "Please add an alias for "google-chrome" to your CLI environment."

### ISSUE THREAD

**Issue by loopy3025** [docksal/drupal7-advanced#10] opened 2018-04-05 15:42 UTC
I've been trying to follow the instructions for using Behat and Docksal. The site fires up in our regular browser just fine, but after I include selenium in the Docksal yml file, the driver is included, but behat still can't find Chrome.  

![image](https://user-images.githubusercontent.com/6729935/38376261-37d0edee-38c6-11e8-9b9f-37c8723d3a90.png)

Have I configured the behat.yml wrong?

```
# Docker profile.
# For use inside the CLI container in Docksal.
docker:
  extensions:
    Behat\MinkExtension:
      # URL of the site when accessed inside Docksal.
      base_url: http://web
      # Configure browser to be used. Browser must be available on wd_host.
      # Stick with chrome by default. It's 2x faster than firefox or phantomjs (your results may vary).
      browser_name: chrome
      selenium2:
        wd_host: http://browser:4444/wd/hub
        capabilities: { "browser": "chrome", "version": "*" }
    Drupal\DrupalExtension:
      drupal:
        # Site docroot inside Docksal.
        drupal_root: /var/www/docroot
      drush:
        # Site docroot inside Docksal.
        root: /var/www/docroot
default:
  suites:
    default:
      paths:
        - %paths.base%/features
  extensions:
    Behat\MinkExtension:
      default_session: goutte
      browser_name: chrome
      javascript_session: default
      goutte: ~
      files_path: "%paths.base%/media"
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: "drupal"
    jarnaiz\JUnitFormatter\JUnitFormatterExtension:
        filename: report.xml
        outputDir: %paths.base%/build/tests
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      image_drivers:
        local:
          screenshot_directory: /tmp

```
Note that this is a BLT-built Drupal instance.

Thanks for any help you can provide.

**Comment by loopy3025** [comment] 2018-04-05 15:56
Perhaps this issue is related to behat and BLT and the container not having the appropriate chrome driver? What driver should I be using and how do I get BLT/behat to notice it has been initialized in docksal?

**Comment by achekulaev** [comment] 2018-04-05 19:53
@loopy3025 there is an example project https://github.com/docksal/qa-suite
I suggest you to start from there as I don't think we will be able to assist with custom Behat errors.

**Comment by lmakarov** [comment] 2018-04-05 20:44
Looks like BLT is using Headless Chrome directly (without Selenium) by default. That explains the exception you are getting. It comes from here:
https://github.com/acquia/blt/blob/9.x/src/Robo/Commands/Tests/BehatCommand.php#L213

In Docksal, there is no Chrome (or Firefox) in the `cli` container. Instead, a headless browser is running in a separate `browser` container, controlled via Selenium (we are using the [official selenium images](https://hub.docker.com/r/selenium/) from Docker Hub).

I don't know if there is a way to configure BLT to use a remote Selenium instance.
I'd recommend searching the BLT issues queue. E.g. [this](https://github.com/acquia/blt/issues/2225#issuecomment-340889179)

**Comment by loopy3025** [comment] 2018-06-04 19:13
Response from @grasmash
https://github.com/acquia/blt/issues/2719

**Comment by lmakarov** [comment] 2018-06-04 21:01
@loopy3025 

> BLT currently requires that google chrome be installed in the same container as BLT. 

You can extend `docksal/cli` with a custom `Dockerfile` and install Chrome there
https://docs.docksal.io/en/develop/advanced/extend-images/

At some point, we may add another stock image, that would be derived from `docksal/cli` and have headless Chrome and/or Firefox pre-installed.

**Comment by loopy3025** [comment] 2018-06-05 14:50
Okay. I'll have a look at that. Thanks.

**Comment by justinlevi** [comment] 2018-09-23 18:46
@lmakarov Any updates on this? Without having chrome installed in the same container, it definitely increases the barrier to entry on project requiring BLT. 

Referencing this issue here: https://github.com/acquia/blt/issues/2719

**Comment by lmakarov** [comment] 2018-09-24 19:00
@justinlevi regarding my previous comment:

> At some point, we may add another stock image, that would be derived from docksal/cli and have headless Chrome and/or Firefox pre-installed.

There have been no efforts or plans to do this yet. It also feels like a workaround vs solving the root cause of the issue, which is adding support for remote Selenium/Chrome instances in BLT. None of my projects are using BLT, so I cannot give you an estimate on when this would be looked at. As such, I'm going to close this issue for the time being.

**Closed by lmakarov** 2018-09-24 19:00 UTC
Labels: question

**Comment by brooke-heaton** [comment] 2018-09-25 20:32
@loopy3025 did you ever get this working with BLT?
